# Oracle database configuration
default: &default
  adapter: oracle_enhanced
  host: <%= ENV.fetch("ORACLE_HOST", "localhost") %>
  port: <%= ENV.fetch("ORACLE_PORT", "1521") %>
  database: <%= ENV.fetch("ORACLE_DATABASE", "XE") %>
  username: <%= ENV.fetch("ORACLE_USERNAME", "clientes_user") %>
  password: <%= ENV.fetch("ORACLE_PASSWORD", "clientes_pass") %>
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", "5") %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("ORACLE_DATABASE", "XE") %>

test:
  adapter: sqlite3
  database: ":memory:"
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: <%= ENV.fetch("ORACLE_DATABASE", "XE") %>