source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.4.7'

# Core Rails gems
gem 'rails', '~> 7.1.0'
gem 'puma', '~> 6.0'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'sprockets-rails', '>= 3.4.0'

# MongoDB
gem 'mongoid', '~> 8.0'

# API gems
gem 'jbuilder', '~> 2.7'
gem 'rack-cors'
gem 'httparty'
gem 'json'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Development and test gems
group :development, :test do
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'mongoid-rspec'
  gem 'debug', platforms: [:mri, :mingw, :x64_mingw], require: 'debug'
end

group :development do
  gem 'web-console', '>= 4.1.0'
  gem 'listen', '~> 3.3'
  gem 'spring'
end
